envname: HuskyNavigateEnv
model_id: space7

target_orn: [0.004, -0.009, -3.114]
target_pos: [-12.501, 5.042, 0.161]
initial_orn: [0.004, -0.009, -3.114]
initial_pos: [-7.501, 5.042, 0.161]

fov: 1.57
is_discrete: true
use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 1
ui_components: [DEPTH]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

output: [nonviz_sensor, depth]
resolution: 128

speed:
  timestep: 0.01
  frameskip: 1

mode: headless #gui|headless
verbose: false
