#Environment Specifications--------------
envname: HuskyNavigateEnv
model_id: Euharlee
target_orn: [0, 0, 0]
target_pos: [-1,2,0.3]
initial_orn: [0, 0, 1.57]
initial_pos: [-2,-6,0.3]

#Robot Specifications--------------------
robot_scale: 0.5
power: 2.5
control: torque

#Train Parameters------------------------
n_step: 350
n_episode: 50
n_iter: 92 #(100 Iteration)
#n_iter: 137 #(150 Iteration)

#Learning Method
waypoint_active: false
curriculum: false
elm_active: false
test_set: false

#Screen & UI Parameters------------------
fov: 1.57
is_discrete: true
use_filler: true
display_ui: true
show_diagnostics: true
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.0, 0.0]
  random_init_rot_range: [-0.57, 0.57]

output: [nonviz_sensor, depth]
resolution: 128
speed:
  timestep: 0.01
  frameskip: 3

#Mode Parameters-------------------------
mode: gui #gui|headless #web_ui
verbose: true
fast_lq_render: true
enjoy: false
enable_ui_recording: false