#Environment Specifications--------------
envname: HuskyNavigateEnv
model_id: Euharleek"
target_orn: [0, 0, 0]
target_pos: [-1, -6, 0.3]
initial_orn: [0, 0, -2.8]
initial_pos: [-2, 2, 0.3]
waypoint_active: true

#Robot Specifications--------------------
robot_scale: 0.4
power: 3.35

#Train Parameters------------------------
n_step: 350
n_batch: 100
n_iter: 191
elm_active: false

#Screen & UI Parameters------------------
fov: 1.57
is_discrete: true
use_filler: true
display_ui: true
show_diagnostics: true
enable_ui_recording: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose: false
  random_target_pose: false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.0, 0.0]
  random_init_rot_range: [-0.1, 0.1]

output: [nonviz_sensor, depth, rgb_filled]
resolution: 128
speed:
  timestep: 0.01
  frameskip: 10

#Mode Parameters-------------------------
mode: gui #gui|headless #web_ui
verbose: true
fast_lq_render: true

#For Observe Results---------------------
enjoy: false
