#Environment Specifications--------------
envname: HuskyNavigateEnv
model_id: Euharlee
target_orn: [0, 0, 0]
target_pos: [-0.77,-4.571,0.3]
initial_orn: [0, 0, 3.097]
initial_pos: [-1.968,3.558,0.3]
waypoint_active: true

#Robot Specifications--------------------
robot_scale: 0.4
power: 3.35

#Train Parameters------------------------
n_step: 300
n_batch: 100
n_iter: 91 #(100 Iteration)
elm_active: false

#Screen & UI Parameters------------------
fov: 1.57
is_discrete: true
use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.0, 0.0]
  random_init_rot_range: [-0.1, 0.1]

output: [nonviz_sensor, depth]
resolution: 128
speed:
  timestep: 0.01
  frameskip: 3

#Mode Parameters-------------------------
mode: headless #gui|headless #web_ui
verbose: false
fast_lq_render: false

#For Observe Results---------------------
enjoy: false
enable_ui_recording: false