#Environment Specifications--------------
envname: HuskyGibsonFlagRunEnv
model_id: space7
target_orn: [0.004, -0.009, -3.114]
target_pos: [-11.525, 21.086, 0.148]
initial_orn: [0.004, -0.009, -3.114]
initial_pos: [-9.919, 20.864, 0.148]

#Robot Specifications--------------------
robot_scale: 0.6
power: 2.75

#Train Parameters------------------------
n_step: 700
n_batch: 35
n_iter: 30

#Screen & UI Parameters------------------
fov: 1.57
is_discrete: true
use_filler: true
display_ui: true
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose : false
  random_target_pose : true
  random_init_x_range: [-1, 1]
  random_init_y_range: [-1, 1]
  random_init_z_range: [-0.0, 0.0]
  random_init_rot_range: [-0.1, 0.1]

output: [nonviz_sensor, depth]
resolution: 128
speed:
  timestep: 0.01
  frameskip: 1

#Mode Parameters-------------------------
mode: gui #gui|headless #web_ui
verbose: true
fast_lq_render: true